spring:
  application:
    name: pos-gateway
  freemarker:
    template-loader-path:
      - classpath:/templates
    suffix: ftl
    charset: UTF-8
    check-template-location: false
    expose-spring-macro-helpers: true

  #MYSQL DATASOURCE
  datasource:
    url: jdbc:mysql://localhost:3306/posDB
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 60000
      max-lifetime: 30000
      connection-timeout: 60000
      pool-name: HikariConectonPoolIPSLDatabase
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

configs:
  mpesa-stk-endpoint: https://api.safaricom.co.ke/mpesa/stkpush/v1/processrequest
  mpesa-auth-endpoint: https://api.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials
  mpesa-consumer-key: KbIb5w8D2Be7OLXJayJOhwxicxxhzXhw
  mpesa-secret-key: 0bPTugYG0mNjIKRg
  mpesa-grant-type: client_credentials
  mpesa-business-short-code: 552055
  mpesa-call-back: https://pos-gateway.visystem.net/api/v1/gateway/mpesa/callback
  mpesa-pass-key: 970bdbce9189ea2d7a7f24de6275057b4fed6ec34afcb0c7087777d0db05c887
  sms-endpoint: https://api.africastalking.com/version1/messaging/bulk
  sms-api-key: MyAppApiKey



